### PR TITLE
Bump Release to 1.0.2

### PR DESCRIPTION
**Pull request by joshua-oss**
* Update snsql dependency to 1.0.2 to take advantage of bug fix in `approx_bounds`
* Fix bug where MST synthesizer would raise warning but attempt to keep running when `mbi` not installed
* Update documentation to highlight `mbi` dependency

Addresses #573

### CODE REVIEW

**Comment by ocolluphid** [comment]
@joshua-oss question re. this update to the MST code: does this mean that the tutorial [here](https://github.com/opendp/smartnoise-sdk/blob/main/synth/samples/mst_sample/mst_sample_pums.ipynb) regarding domain use is no longer up to date and we should defer to this: https://docs.smartnoise.org/synth/synthesizers/mst.html

**Comment by joshua-oss** [comment]
Yes, that code sample still should work (we haven't done anything to disable it) but it's better to use the common pattern used across all the synthesizers. Note that I recently discovered an issue where MST and AIM are failing if the inferred cliques overlap in a certain order, so if you're seeing errors like "column_name is both an index and a level", it's a bug that I haven't yet tracked down.

**Comment by ocolluphid** [comment]
sounds good! mainly asking because it seems like the new style no longer requires domain specification and I'm guessing that's being automated in the background?

**Comment by ocolluphid** [comment]
thanks! will defer to latest one without domain specification then.

**Pull request merged**
