### PR TITLE
DRAFT:fix_load_meta

### PR DESCRIPTION
**Pull request by vserret**
Fix load_symbols in queries when 
- the GROUP BY clause uses aliases from the SELECT clause 
e.g.: `SELECT "IsHoliday" As col, SUM(features."Store") FROM features GROUP BY col;` or `SELECT "IsHoliday" As "Col", SUM(features."Store") FROM features GROUP BY "Col";`
- they is more than one table. e.g.: `SELECT "Temperature", AVG("Weekly_Sales") FROM features, sales;`

### CODE REVIEW

**Review by joshua-oss — APPROVED** [review]
Looks good!  I added two unit tests.

**Comment by vserret** [comment]
@joshua-oss I have made changes for loading data into queries like `SELECT features."Store", sales."Store" FROM features, sales;` where their is two tables with the same colnames

**Review by joshua-oss — APPROVED** [review]

**Comment by joshua-oss** [comment]
This looks great!  Thanks for advancing the multi-table support

Do you want to merge now, or were you planning to do some more work in the branch before merging.

**Comment by joshua-oss** [comment]
I will merge this now, so I can merge back into the PR to override sensitivity

**Pull request merged**
